### ISSUE TITLE
Seed Markov plugin

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#101]
Eg. `/markov my name is`.

**Comment by avipatel91** [comment]
Interesting. I assume there will also be a response to this? Really helpful for FAQs, where user can ask similar question and plugin responds with answer based on markov model.

**Comment by CapacitorSet** [comment]
The way they are now, Markov chains can't be used to write FAQs, because they don't understand the content of text at all - they just spit out some text that reuses known pairs of words.
