### ISSUE TITLE
Use proper API for showing images

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#112]
Currently, the BoobsButts and Reddit plugins send a link to the image. They should send the picture instead, using the Util function for downloading a resource to disk.

**Comment by CapacitorSet** [comment]
Actually, it seems that you can pass an image URL to Telegram directly. Use that instead.

**Comment by avipatel91** [comment]
The behavior is the same whether you send the url via text or photo. Telegram still displays the image with the url. Is it different on mobile?

**Comment by CapacitorSet** [comment]
Is it? I didn't try it out, but it appears that if you send it by text it will display the URL with an optional image preview, whereas using [`sendPhoto`](https://core.telegram.org/bots/api#sendphoto) you can pass an URL from which the Telegram server will download an image and display it as a standalone picture.
