### ISSUE TITLE
Doesn't work on Node <6

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#113]
It seems that the bot doesn't work with versions of Node previous to 6.0. There ought to be a check on "npm firstrun".

**Comment by crisbal** [comment]
We should use `package.json`'s `engines` field: https://docs.npmjs.com/files/package.json#engines

**Comment by CapacitorSet** [comment]
I'm not sure, is the `engines` field taken into consideration if the user cloned the repository rather than doing `npm install`?
