### ISSUE TITLE
Add Spoiler plugin - hideitbot like

### ISSUE THREAD

**Issue by FerdinandoLM** [Telegram-Bot-Node/Nikoro#114]
HideItBot is (was?) a bot very nicely working but seems to be offline. 

It would be great to add a plugin like hideit bot, knowing that that bot is opensource: https://github.com/erpheus/hideit-bot

**Comment by crisbal** [comment]
Right now our bot/framework does not support interfacing with buttons and custom keyboards, first we will need to add support for these backend features.
