### ISSUE TITLE
Implement unset for MediaSet

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#123]
Mediaset provides /mset, but not /munset.

**Comment by FerdinandoLM** [comment]
Totally (not) serious proposal: rename the unset command to /moonset

**Comment by Ichicoro** [comment]
Working on it! @FerdinandoLM I could do that 🤔

**Comment by CapacitorSet** [comment]
Fixed in #148 with the /moonset Easter egg.
