### ISSUE TITLE
Update the wiki

### ISSUE THREAD

**Issue by Ichicoro** [Telegram-Bot-Node/Nikoro#124]
The wiki needs to be updated: there's a lot of instances where examples use the old syntax (eg: `import Foo from "Foo.js"` instead of `const Foo = require("Foo.js")` and `export default class Bar extends Plugin` instead of `module.exports = class Bar extends Plugin`)

**Comment by CapacitorSet** [comment]
Fixed. Link to the new guide: https://github.com/crisbal/Telegram-Bot-Node/wiki/Plugins
