### ISSUE TITLE
Improve Forward.js

### ISSUE THREAD

**Issue by neslinesli93** [Telegram-Bot-Node/Nikoro#125]
Hi guys thanks for your hard work - I love the bot!
Could you please reintroduce the /chan or #chan function?
Make Chan Great Again!

Thanks,
Tommaso

**Comment by CapacitorSet** [comment]
Tldr: make Forward.js work on private channels

**Comment by neslinesli93** [comment]
What does it mean? Hopefully it's an internal memo or something like that

**Comment by FerdinandoLM** [comment]
Can you please explain what function should "/chat" or "#chat" do?

**Comment by CapacitorSet** [comment]
Actually, Forward.js *does* work, it's just that it's hard to get the chat ID for a private channel.

@crisbal, should we do something about that?

**Comment by CapacitorSet** [comment]
Actually, Forward.js *does* work, it's just that it's hard to get the chat ID for a private channel.

@crisbal, should we do something about that?

**Comment by CapacitorSet** [comment]
Note: add support for #fwd/#chan
