### ISSUE TITLE
Add Urban Dictionary plugin

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#126]

**Comment by caleywoods** [comment]
I can work on this one, I've done a Twilio SMS script for Hubot before so this should be somewhat similar.

@CapacitorSet - Do you just envision that this plugin takes a word or phrase from the chat input (or given to the bot) and uses the Urban Dictionary API to return both a definition of the word/phrase as well as a link to view the definition on UD?

**Comment by CapacitorSet** [comment]
Yes, pretty much. Something like the following:

>User: /ud

>Bot: **telegram**: A once-popular system of telecommunications, in which the sender would contact the telegram service and speak their message over the phone.  The person taking the message would then send it, via a teletype machine, to a telegram office near the receiver's address.  The message would then be hand-delivered to the addressee.  From 1851 until it discontinued the service in 2006, Western Union was the best-known telegram service in the world.
>
>*Hey, let's send Mom a telegram for her birthday! She just loves receiving that little yellow envelope.*

Since you're at it, could you try writing your plugin based on the documentation in the [wiki](https://github.com/crisbal/Telegram-Bot-Node/wiki/)? You would help spot any missing or incorrect information.

**Comment by caleywoods** [comment]
Will do, I believe you meant the usage to be:

> User: /ud telegram

And then the bot respond with what you queried

**Comment by CapacitorSet** [comment]
Oh welp, indeed.

**Comment by caleywoods** [comment]
One of the things I found upon initial setup that may be a stumbling point for new users:

Running `npm run firstrun`, when it's nearly finished will ask you for an array of user ID's to treat as global admins. I did not try to skip this, though I assume you can. It seems like a user has two options during this step:

* Skip it by pressing `ENTER` and optionally adding them later in `config.json` under `"globalAdmins"`

* Find their Telegram user_id with the following steps
    * Search Telegram for what they named their bot, send it a test message
    * Visit (or make a `GET` to) https://api.telegram.org/botYOUR-API-KEY/getUpdates (replace YOUR-API-KEY with the key you pasted earlier in the setup process, BotFather gives you this when you register a Telegram bot) which will return some json. The key `result` will be an array of objects, each containing a `message` key that is an object, this object has a key called `from` which has a property called `id` this is your user ID. In my case that was: `result[0].message.from.id` if you're looking at it from a response versus in the browser.

Please be aware this relies on someone else not having messaged your bot before you do. If you think that's the case then just `console.log(data.result)` and look through the messages, expanding `from` on each until you find a message with your name. Chances are high that the first message will be from you.

**Comment by CapacitorSet** [comment]
Hmm, indeed, that's not super friendly. You're welcome to make a PR - though, remember that in order to count towards the Hacktoberfest they must be opened after October 1.

I opened [a new issue](https://github.com/crisbal/Telegram-Bot-Node/issues/135) about that, and wrote down a couple of notes on how I'd fix that. If you wish to "claim" it (perhaps in occasion of the Hacktoberfest) just let us know in the linked issue.

**Comment by caleywoods** [comment]
I'll focus on this issue for now. When I go to send the PR if the other isn't claimed i'll take a stab at fixing the documentation, I think the setup script is working well.

**Comment by caleywoods** [comment]
How's this looking?

![Example of Urban Dictionary Plugin](https://i.imgur.com/yTG4Ym8.png)

**Comment by CapacitorSet** [comment]
Looks just right! However, why the long space between the beginning of the line and the example usage?

**Comment by caleywoods** [comment]
Not sure, I'll try tweaking it later on. Not sure if it's my "formatting" in the template string or something else.

**Comment by caleywoods** [comment]
Fixed. I replaced my returns with two new line characters.

https://i.imgur.com/mWTlzRs.png

**Comment by CapacitorSet** [comment]
Sounds good.

**Comment by CapacitorSet** [comment]
Fixed in #139.
