### ISSUE TITLE
Add warning about callback usage in docs?

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#131]
If using callbacks inside onText/onCommand, one can make this mistake, as already [happened](https://github.com/crisbal/Telegram-Bot-Node/issues/129#issuecomment-332057415) [twice](https://github.com/crisbal/Telegram-Bot-Node/issues/129#issuecomment-332060254):

```js
request("http://google.com", function(err, response) {
    if (err) throw err;
    this.sendMessage("Request successful!");
});
```

This is incorrect, because the `this` in `this.sendMessage` is [the global object](https://stackoverflow.com/a/134149), not the Plugin instance. Instead, one must use an arrow function: `(err, response) => { ... }`.

This error may not be immediately obvious to plugin developers, so it should be documented in the wiki.

**Comment by martiuslim** [comment]
seems like you have already added this to the wiki [here](https://github.com/crisbal/Telegram-Bot-Node/wiki/Plugins/_compare/13dacc1d9f95708a09fa9173f72e49533fd0adb8) :smile:

**Comment by CapacitorSet** [comment]
Oh well, I forgot to update the issue. Thank you!
