### ISSUE TITLE
Persist /enable, /disable to config.json

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#136]
Expected behaviour: `/enable <plugin>` keeps that plugin enabled "forever", even across bot restarts.

Actual behaviour: the plugin is only enabled until the next shutdown. It won't be saved to config.json, so when the bot starts next time, the plugin will no longer be enabled.

Solution: PluginManager.loadAndAdd/PluginManager.removePlugin should save the plugin in the new configuration, and save the configuration to disk.

**Comment by LucasLeandro1204** [comment]
I can get this one.

**Comment by CapacitorSet** [comment]
Very well! Don't forget that for pull requests to count towards the Hacktoberfest, they must be opened on October 1 or later.

If you need help navigating through the codebase or otherwise have questions, feel free to ask.

**Comment by LucasLeandro1204** [comment]
@CapacitorSet I know it xd, but the code seems pretty easy, I will create a function to save the config json and that's it, I just have to see how I use telegram huahuauhauha

**Comment by CapacitorSet** [comment]
@LucasLeandro1204 are you still planning to implement this?

**Comment by LucasLeandro1204** [comment]
@CapacitorSet Sure I will haha, today I do this.

**Comment by CapacitorSet** [comment]
@LucasLeandro1204, please don't take up issues if you're not going to fix them.
