### ISSUE TITLE
Avoid flooding command requests

### ISSUE THREAD

**Issue by Mte90** [Telegram-Bot-Node/Nikoro#31]
The spam with the bot can be very annoying so a little check about many commands from the same person can improve that behaviour.

**Comment by crisbal** [comment]
Will definitely consider this for the next major release, which should be coming in the next weeks / months.

**Comment by CapacitorSet** [comment]
Fixed in 183ef4af5534591b663a5b98ab21734a9a284b7b with a basic algorithm: messages less than 1000 ms apart will be discarded.

It was pushed to a development branch, which will eventually be merged with `master` as @crisbal said.

**Comment by Mte90** [comment]
amazing guys!
