### ISSUE TITLE
Add user stats plugin

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#59]

**Comment by crisbal** [comment]
Let's consider stats-ing different message types

**Comment by avipatel91** [comment]
Hi, I was wondering exactly what stats would be given? Also, what would be the input? Would it be the username or is that given implicitly?

**Comment by CapacitorSet** [comment]
Hello, thanks for your interest!

The goal of the plugin is to replicate what is currently implemented in @rTARS, which says:

```
Total messages: 355335

Foo Bar [12345678]: 52347 (14.7317%)
Some User [xxxxxxx]: 34506 (9.7108%)
Some Other User [xxxxxxx]: 19758 (5.5604%)
```

You can find help on writing plugins in [`docs/Plugin.md`](https://github.com/crisbal/Telegram-Bot-Node/blob/es6/docs/Plugins.md). You'll want to write a Proxy plugin: a good start is [`src/plugins/Logger.js`](https://github.com/crisbal/Telegram-Bot-Node/blob/es6/src/plugins/Logger.js). Note that all work happens on the `es6` branch.
