### ISSUE TITLE
Create a landing page for the project. Naming the bot.

### ISSUE THREAD

**Issue by crisbal** [Telegram-Bot-Node/Nikoro#6]
It would be cool to have a landing/home page for the project, where we present its main features. 

It is **not a priority** right now, especially because we don't have much to show, but in the future it could be a good thing to implement. 

I'd like to take care of it since Web Development is something I enjoy.

**Comment by phillfarrugia** [comment]
I agree this would be great to do.

In addition to this, we should find a nifty name for the project too. Perhaps something nerdy and bot related?

Existing ones:
- Hubot
- Slackbot
- BotFather

**Comment by crisbal** [comment]
Well, I called it Node-Telegram-Bot, since it is based on Node, its made for Telegram and is a Bot. Not really that original and interesting.

The problem is that there are already two repo with the same name: 
* https://github.com/orzFly/node-telegram-bot 
* https://github.com/depoio/node-telegram-bot

Which are just two wrapper for the API.

I really suck at naming things, just look at the name of my other projects :smile: 

I came up with Nobot (Node+Robot) but I am not sure, having "no"+"bot" in the name seems like a slogan for someone that hates bots.

**Comment by crisbal** [comment]
Also I could post the bot on https://news.ycombinator.com/ to give it some visibility.

**Comment by phillfarrugia** [comment]
I don't know why, but I started thinking of Jetsons characters because they're all futuristic and robot-y.

What if we named the project after one of those characters 😜 and than see if there's any copyright issues with using their likeness as a 'logo' of sorts?

If not Jetsons, take a look at [this list of fictional 'butlers'](https://en.wikipedia.org/wiki/List_of_fictional_butlers) and see if anything seems interesting.

Elroy? 
<img src="http://vignette3.wikia.nocookie.net/hanna-barbera/images/8/89/Elroy_Jetson.png/revision/latest?cb=20110327083337" width="100">

Astro? 
<img src="http://vignette3.wikia.nocookie.net/hanna-barbera/images/3/36/Dogs-astro.png/revision/latest?cb=20110206031013" width="100">

Rosie?
<img src="http://vignette3.wikia.nocookie.net/p__/images/4/44/Rosie.jpg/revision/latest?cb=20120305141357&path-prefix=protagonist" width="100">

**Comment by crisbal** [comment]
**Elroy** is cool. 

I don't think we would have any copyright issue, it is just a person name, not a company name or something.

Also if we go with this, does this mean that we have to rename the repo? from crisbal/Node-Telegram-Bot to crisbal/Elroy ? Or we can leave the Repo URL as it is and just change the name in the readme and in a few other places? 

The current URL is pretty good from the SEO (Search Engine Optimization) point of view, people search for Node Telegram Bot and they probably get this because of the URL matching (right now it doesn't really do that, the project doesn't show on Google Search, will look into that), but if we change the URL to just Elroy it will be hard for people to find it, until a landing page is complete, at least.

**Comment by phillfarrugia** [comment]
My suggestion would be we should rename the repo to crisbal/Elroy, Node-Telegram-Bot is very generic and while it might be okay for SEO there are other ways to be even better at SEO and discovery.

If we have a landing page for one. If we maybe write a blog post about it, and post it on a subreddit/hacker news as you mentioned. There are a lot of others that are just simply called 'Node-Telegram-Bot', but if we can make ours look more polished, people will be more likely to stick around and use it. Hopefully eventually we can mention it to Telegram on twitter or something (when it's better) and they'll share it for us too!

Again we don't need to do this immediately, just food for thought

**Comment by crisbal** [comment]
Seems good to me. :+1:

**Comment by CapacitorSet** [comment]
If everyone is okay with the name change, I'd like to ask @crisbal to rename the project. I'll also open a new issue for the landing page, to keep track of it more easily.

**Comment by blackdev1l** [comment]
:+1: for Elroy

**Comment by CapacitorSet** [comment]
I developed a landing page on the `gh-pages` branch (temporary URL: http://baldi.me/Telegram-Bot-Node); we now have to pick a name.

**Comment by CapacitorSet** [comment]
Closed. We picked Nikoro, and the landing page is now at https://telegram-bot-node.github.io/Nikoro/.
