### ISSUE TITLE
Voting plugin

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#61]
We need a voting plugin (split from #17).

**Comment by malhar12** [comment]
Hello @CapacitorSet ,

A voting plugin, sounds an interesting idea. I would like to get my hands dirty with it. Can you give me an explanation, with which I can start with.

**Comment by CapacitorSet** [comment]
Hello, thanks for your interest!

You can find help on writing plugins in [`docs/Plugin.md`](https://github.com/crisbal/Telegram-Bot-Node/blob/es6/docs/Plugins.md); you can find a sample plugin in [`src/plugins/ImageSearch.js`](https://github.com/crisbal/Telegram-Bot-Node/blob/es6/src/plugins/ImageSearch.js). Note that all work happens on the `es6` branch.

As for the voting plugin in particular, there is no plan yet, you're free to design it as you wish - just use the plugin standards.

**Comment by CapacitorSet** [comment]
Fixed in 021cc6f1a8ea4c4abc98d24934a5f97cd23d4047.
