### ISSUE TITLE
Wiki plugin

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#62]
We need a plugin to search Wikipedia (split from #17).

**Comment by amitkumarj441** [comment]
Hey @CapacitorSet ,

I would like to take up this task. Can you please elaborate more "To search Wikipedia", or to search wikipedia articles?
And where (folder) should I initiate the PRs?

**Comment by CapacitorSet** [comment]
Hello, thanks for your interest!

The original idea was to have a simple plugin to access wikipedia articles, eg. `!wiki Telegram` would return `https://en.wikipedia.org/wiki/Telegram`. To make it different from the @wiki bot, maybe it could have support for different languages (`!wiki lang=it Telegram`, maybe?), or - I don't know.

Plugins belong in `src/plugins`, in the `es6` branch. You can find help on writing plugins in `docs`.

**Comment by amitkumarj441** [comment]
@CapacitorSet Glad to hear from you, I'll check it right away and I'll soon initiate a PR for wiki!
