### ISSUE TITLE
README fixes for es6 branch

### ISSUE THREAD

**Issue by avipatel91** [Telegram-Bot-Node/Nikoro#72]
We are unable to run the app following the instructions under 'Running the bot' section in the README of the es6 branch. Some of the instructions need to be changed in order to get the app to run. This is specific to es6 branch only.

**Comment by CapacitorSet** [comment]
Do you have more information, eg. an install log? What error do you run into, exactly?

**Comment by avipatel91** [comment]
The app simply won't run if you follow the instructions and run `node Bot.js`. This is because the bot.js file no longer exists in project root. Also, we have to account for transpiling the code. 
I have fixed it in the following: 6c875f7da951bd7c21c049f7ba0bd020485b9a8a
I'll make a PR for it.

Picture of error when trying to run app.
<img width="856" alt="screen shot 2016-10-17 at 12 31 51 am" src="https://cloud.githubusercontent.com/assets/11547815/19428841/4c44038a-9401-11e6-9c1d-749c9afae479.png">

**Comment by CapacitorSet** [comment]
Can you try `bash install.sh`? The issue of making the installation process easier was discussed in #24, and we eventually made a bash script to automate that.

**Comment by avipatel91** [comment]
I ran the script and it works. Thanks! By the way, shouldn't the instructions still be changed for es6 branch since nowhere in the readme does it say to run `./install.sh`. Want me to create PR to update the documentation?

**Comment by CapacitorSet** [comment]
Thank you for your willingness to help. However, I also noticed that `setup.sh` wasn't mentioned anywhere in the README (probably because it was a WIP), so I fixed that in 8b520ff28d2ef70e532c7ab23c84abf503f92039.

Anyway, I'll close this issue since it was fixed successfully.
