### ISSUE TITLE
Quote system

### ISSUE THREAD

**Issue by blackdev1l** [Telegram-Bot-Node/Nikoro#77]
I'll do it

**Comment by CapacitorSet** [comment]
What do you mean? Something like !quote, !addquote in TARS?

**Comment by blackdev1l** [comment]
http://forum.egghelp.org/viewtopic.php?t=13997

**Comment by blackdev1l** [comment]
Thanks for the assignee, i'll try to give the basic functionality ready today, the basic commands will be: 
- /addquote
- /delquote
- /quote <number>
- /quote  (it gives a random quote)

**Comment by blackdev1l** [comment]
Done #85

**Comment by CapacitorSet** [comment]
Finally fixed in 687b0fd6bab005ae6f1881956eff94e31a894a33!
