### ISSUE TITLE
Limit regex set, make a "traditional set" plugin

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#80]
RegexSet can be used to spam a lot, eg. `/regexset . - SPAM` will reply to every message - make 10 such regexsets, and you've got a huge spam multiplier.

It was suggested in chat that we restrict the usage of RegexSet to trusted users with the "permission to spam" (i.e. mods), and make a "traditional set" plugin open to everyone.

The traditional set plugin will work like !set in @rtars, matching only the first word in a sentence.

Ping @crisbal and @blackdev1l to discuss this. If it's okay, we can either split that into two issues and work on them, or just push the fix and close this issue in the same day.

**Comment by FerdinandoLM** [comment]
My thought is that Regex is way too powerful to be left to users in high message traffic groups.

I suggest some sort of whitelist (where it should preferably be stand alone from other whitelists, altough this could be too much effort on a single plugin) like mod or a global whitelist.

**Comment by CapacitorSet** [comment]
Traditional set implemented in 461e93567c7509946e5a940d8f17a6a9bcf22102.
