### ISSUE TITLE
Welcome & Goodbye plugin

### ISSUE THREAD

**Issue by FerdinandoLM** [Telegram-Bot-Node/Nikoro#83]
Add a plugin that welcomes and says goodbye when a user joins / leaves the chatroom.

In addition to that, the bot shoud always attach the user id of the user who joined/left in order to be able to perform moderation actions. 

In many cases spam users joins groups and leave the group just before some action could be done.

**Comment by CapacitorSet** [comment]
We already have a [Welcome plugin](https://github.com/crisbal/Telegram-Bot-Node/blob/es6/src/plugins/Welcome.js), by the way; it just needs small fixes to say goodbye when a user leaves. If you want, you can work on that.

The point about user ids isn't necessary, if one uses the Kick plugin they can simply reply to the enter/exit notification with /ban.
