### ISSUE TITLE
Port dev plugins to ES6

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#84]
- [x] 8ball
- [x] boobsbutts
- [x] echo
- [x] googleimage
- [x] google
- [x] imgur
- [x] karma
- [x] math
- [x] ping
- [x] quote
- [x] reddit
- [x] reverse
- [x] roll
- [x] set
- [x] text
- [x] twitch
- [x] vote
- [x] xvideos
- [x] youtube

**Comment by avipatel91** [comment]
Are these up for grabs?

**Comment by CapacitorSet** [comment]
Yes. However, note that some of these are inline-only, eg. reverse ([see `this.properties`](https://github.com/crisbal/Telegram-Bot-Node/blob/dev/plugins/reverse.js#L8)), so they can't be implemented right away.

**Comment by CapacitorSet** [comment]
_We did it_ (dbced6271c1f058209766c250e671dc02767c089)!
