### ISSUE TITLE
"Events" plugin

### ISSUE THREAD

**Issue by DDF95** [Telegram-Bot-Node/Nikoro#93]
Introdurre un plugin `events` o comunque una sorta di remindme per organizzare gli eventi in chat o altrove.
`/events` apre una sorta di calendario con data e ora dell'evento (e magari anche il nome di chi ha creato l'evento). Sarebbe carino anche mettere accanto ad ogni evento "mancano X giorni, X minuti ed X secondi".
Per aggiungere un evento o un promemoria: `/addevent dd/mm/yyyy hour:minute:second text`. Non serve aggiungere per forza i secondi o minuti esatti, in modo da rendere più veloce la scrittura del comando.

**Comment by CapacitorSet** [comment]
For people interested in the Hacktoberfest:

>Add an `events` plugin, as a sort of reminder/calendar for events in the chat.

>`/events` would open something like a calendar with date and time of the event (and maybe also the name of who organized the event). It would also be nice to have a caption like "in X days, X minutes and X seconds".
>To add an event or reminder: `/addevent dd/mm/yyyy hour:minute:second text`, maybe with seconds and minutes optional (defaulting to zero).

**Comment by CapacitorSet** [comment]
Taken by @Ichicoro.
