### ISSUE TITLE
Make user stats message simpler

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#98]
- Remove user ID
- Split userstats into userstats and wordstats

**Comment by avipatel91** [comment]
I can take this one up. Should I split userstats and wordstats into separate plugins? Or does somthing like the following work?  
get user stats:   `/stats user`
get word stats:      `/stats word`

**Comment by CapacitorSet** [comment]
Oh, actually, I have implemented this, though I didn't push the commits yet

If you have some time to contribute, you could copy over the Math plugin from the dev branch to es6. The code is mostly the same, it just needs to use the new boilerplate instead (i.e. onCommand). When this is done, we can eventually close the dev branch and pass to a standard branching model.

Ping @crisbal to keep an eye on this

**Comment by CapacitorSet** [comment]
Fixed in dbc198010ca0212bcecb125de2287601c98cd412
